seed: 1234
data:
  dataset_dir: './datasets/test'
  all_category_names: ['gene', 'disease']
  total_repeats: 10
  is_undirected: True

model: 
  num_epochs: 5
  batch_size: 64
  learning_rate: 0.025
  neg_sample_cnt: 5
  embedding_dim: 128